config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "pages#home"

  resources :organizations, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    resources :members, only: [:create]
    resources :messages, only: [:create, :new]
    resources :tasks, only: [:index, :show, :create, :update]
  end
  resources :users, only: [:index] do
    member do
      get :profile
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  before_save :format_date
  belongs_to :organization

  CATEGORIES = ['Maison', 'Administratif', 'Santé', 'Famille', 'Loisirs', 'Quotidien', 'Autres']
  validates :category, inclusion: { in: CATEGORIES }
  validates :start, timeliness: { on_or_before: lambda { Date.current }, type: :date }
  validates :end, presence: true, comparison: { greater_than_or_equal_to: :start }


  def format_date
    self.start = start.strftime("%d/%m/%Y") if start.present?
    self.end = self.end.strftime("%d/%m/%Y") if self.end.present?
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action :set_task, except: [:index]
  before_action :set_org, only: [:index, :create]
  def index
    @tasks = Task.where(organization: @organization)
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(params_tasks)
    @task.organization = @organization
    
    if params_tasks[:end].nil? && params_tasks[:start].present?
      @task.end = params_tasks[:start]
    else
      @task.end = params_tasks[:start].split('au')[1]
    end

    if @task.save!
      redirect_to organization_tasks_path(organization: @organization)
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(params_tasks)
      redirect_to task_path(@task)
    else
      redirect_to task_path(@task)
            # FAUT CHANGER CA AVEC UNE ALERT
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def set_org
    @organization = Organization.find(params[:organization_id])
  end

  def params_tasks
    params.require(:task).permit(:category, :title, :description, :start, :end, :priority, :status, :recurrence)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task_form.html.erb
<div class="taskform_container">
  <%= form_with(model: [organization, task], method: :post, html: { class: "form", data: { date_form_target: "form" } }) do |f| %>
    <div class="form_input_text">
      <%= f.text_field :title, placeholder: "Qu'avez-vous à faire ?", class: "input_form" %>
      <%= f.text_field :description, placeholder: "Décrivez la tâche", class: "input_form form_desc" %>
      <%= f.select :category, Task::CATEGORIES, { prompt: "Ajoutez une catégorie" }, { class: "input_form" } %>

      <%= f.text_field :start,
                      placeholder: "Sélectionnez une date",
                      data: {
                        controller: "flatpickr",
                        flatpickr_target: "start"
                      },
                      class: "input_form" %>
    </div>
    <div class="urg_btn">
      <div class="urg">
        <%= f.label :priority, "Urgent?" %>
        <label class="switch">
          <%= f.check_box :priority %>
          <span class="slider round"></span>
        </label>
      </div>

      <%= button_tag "Enregistrer", type: :submit, class: "btn-form" %>
    </div>

  <% end %>
</div>

app/views/tasks/index.html.erb
<%= render "shared/top_page" %>
<div class="maincontainer">
  <% if @tasks.any? %>
    <div class="index_tasks">
      <div class="tasks_list">
        <% @tasks.each do |task| %>
          <%= link_to organization_task_path(@organization, task) do %>
            <div class="task_line">
              <div class="task_title"><%= task.title %></div>
              <% if task.status == false %>
                <i class="fa-regular fa-square-check fa-lg"></i>
              <% else %>
                <i class="fa-solid fa-square-check fa-lg"></i>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="link_add_task" data-controller="toggle">
        <button data-toggle-target="button" data-action="click->toggle#toggleEdit">
          <i class="fa-solid fa-plus" style="color: #9927f7;"></i>
        </button>
        <div class="div d-none" data-toggle-target="div">
          <%= render "task_form", task: @task, organization: @organization %>
        </div>
      </div>
    </div>

  <% else %>
    <%= render "task_form", task: @task, organization: @organization %>
  <% end %>

</div>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p>Début le <%= I18n.localize(@task.start) %></p>
<p>Fin le <%= I18n.localize(@task.end) %></p>
<p><%= @task.description %></p>

<% if @task.status == true %>
  <p>Terminé</p>
<% else %>
  <p>En cours</p>
<% end %>

<%= link_to "Retour index", tasks_path %>



<p>Edit Task</p>
<%= simple_form_for @task do |f| %>
  <%= f.input :category, collection: Task::CATEGORIES %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :start, html5: true %>
  <%= f.input :end, html5: true %>
  <%= f.input :priority, label: "Urgent?" %>
  <%= f.input :recurrence %>
  <%= f.input :status, label: "Terminé?" %>
  <%= f.button :submit %>
<% end %>