config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "pages#home"

  resources :organizations, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    resources :members, only: [:create]
    resources :messages, only: [:create, :new]
    resources :tasks, only: [:index, :show, :create, :update]
  end
  resources :users, only: [:index] do
    member do
      get :profile
    end
  end
end

app/models/organization.rb
require 'json'
require 'open-uri'

class Organization < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :messages
  has_many :tasks
  has_many :members
  has_many :users, through: :members

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def meteo
    url = "https://api.openweathermap.org/data/2.5/weather?lat=#{self.latitude}&lon=#{self.longitude}&appid=#{ENV['OPENWEATHER_MAP_API']}&units=metric"
    meteo_serialized = URI.parse(url).read
    meteo = JSON.parse(meteo_serialized)
    icon = meteo['weather'].first['icon']

    {temp: meteo['main']['temp'], icon: "https://openweathermap.org/img/w/#{icon}.png"}

  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, except: [:index, :create]
  # before_action :group_tasks, except: [:index, :create]

  def index
    @organizations = Organization.all
    @organization = Organization.new
  end

  def create
    orga = Organization.new(params_org)
    orga.creator = current_user
    orga.password = BCrypt::Password.create(params_org[:password])
    redirect_to organization_path(orga) if orga.save!
  end

  def show
    @message = Message.new
    @member = Member.new
    @task = Task.new
    @other_users = @organization.users.where.not(username: current_user.username)
    @messages_users = @organization.messages.where.not(user: current_user)
  end

  def destroy
    if @organization.delete
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    if @organization.update(params_org)
      redirect_to organization_path(@organization)
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def set_organization
    @organization = Organization.find(params[:id])
  end

  def group_tasks
    @tasks = @organization.tasks
  end

  def params_org
    params.require(:organization).permit(:name, :address, :password)
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/index.html.erb
<div class="maincontainer">
  <% if !@organizations.empty? %>
    <% @organizations.each do |organization| %>
      <%= link_to organization.name, organization_path(organization) %>
    <% end %>
  <% else %>
    <p>Add Org</p>
    <%= simple_form_for @organization do |f| %>
      <%= f.input :name %>
      <%= f.input :password %>
      <%= f.input :address %>
      <%= f.submit "Add" %>
    <% end %>
  <% end %>
</div>

app/views/organizations/show.html.erb
<%= render "shared/top_page" %>
<div class="maincontainer">

  <div class="cards-orga-infos" data-controller="toggle">

    <div class="pixel-corners pixel-cards">
      <div data-toggle-target="name" class="title_orga">
        <h4><%= @organization.name %></h4>
        <button data-toggle-target="button" data-action="click->toggle#toggle">
        <i class="fa-regular fa-pen-to-square" style="color: #9927f7; margin-top: 2%;"></i>
        </button>
      </div>
      <div data-toggle-target="div" class="d-none">
        <%= render "shared/form", organization: @organization %>
      </div>
    </div>

    <div>
      <% %>
    </div>
    <% if @organization.members.any? %>
      <div class="infos-organization">
        <div class="infos">
          <div class="member_organization">
            <div class="user_org">
              <% @other_users.each do |user| %>
              <div class="user_card">
                <div class="user_info">
                  <% if user.avatar.attached? %>
                    <%= cl_image_tag user.avatar.key, class: "avatar-mini" %>
                  <% else %>
                    <%= image_tag user.avatar, class: "avatar-mini" %>
                  <% end %>
                    <p><%= user.username %></p>
                </div>
                <% messages = @messages_users.where(user: user) %>
                <%= turbo_stream_from "organization_#{@organization.id}_latest_message" %>
                <div class="contentmessage" id="organization_<%= @organization.id %>_latest_message">
                  <%= render "messages/latest_message", message: messages.last %>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% else %>

      <div class="add_member">
        <%= form_with model: @member, url: organization_members_path(@organization), class: "form", local: true do |f| %>
          <%= f.collection_select :user_id, User.where.not(email: current_user.email), :id, :username, { prompt: "Sélectionner un utilisateur" }, { class: "input_form" } %>
          <button type="submit" class="btn-form">
            <i class="fa-solid fa-plus" style="color: #ebd6e4;"></i>
          </button>
        <% end %>
      </div>
    <% end %>

  </div>

  <div class="cards-orga-infos part_tasks">
    <div class="pixel-corners pixel-cards">
      <div data-toggle-target="name" class="title_orga">
        <h4>Tâches</h4>

      </div>
    </div>
    <div class="infos-organization tasks">
      <div class="infos">
        <div class="task_organization">
          <div class="task_org">

            <% if @organization.tasks.any? %>
             <div class="detail_task">
                <p class="number"><%= @organization.tasks.where(status: false).count %></p>
                <p class="descr"><%= @organization.tasks.where(status: false).count > 1 ? 'tâche'.pluralize : 'tâche' %></p>
              </div>

              <div class="detail_task">
                <p class="number <%= @organization.tasks.where(end: Date.today).count >= 1 ? "urgent" : " " %>"><%= @organization.tasks.where(end: Date.today).count %></p>
                <p class="descr">aujourd'hui</p>
              </div>

              <div class="detail_task">
                <p class="number"><%= @organization.tasks.where(priority: true).count %>
                <p class="descr"><%= @organization.tasks.where(priority: true).count > 1 ? 'prioritaire'.pluralize : 'prioritaire' %></p>
              </div>
            <% else %>
              <em><%= link_to "Ajouter votre 1ere tâche !", organization_tasks_path(@organization), class:"link_add" %></em>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>

</div>